set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(CUSTOM_GCC_PATH "custom-gcc-path") # Add path here if there's no system gcc installed.
if (EXISTS ${CUSTOM_GCC_PATH})
	set(CMAKE_FIND_ROOT_PATH ${CUSTOM_GCC_PATH})
	set(CMAKE_C_COMPILER_EXTERNAL_TOOLCHAIN ${CUSTOM_GCC_PATH})
	set(CMAKE_CXX_COMPILER_EXTERNAL_TOOLCHAIN ${CUSTOM_GCC_PATH})
else()
	message(STATUS "no custom GCC found, using system's libstdc++")
endif()
